### ISSUE TITLE
Serving autoscaling strategy

### ISSUE THREAD

**Issue by senysenyseny16** [allegroai/clearml-serving#34]
Hello, ClearML team!

I'm trying to understand how serving auto-scaling works.

From readme:

> Scalable
>    Multi model per container
>    Multi models per serving service
>    Multi-service support (fully seperated multiple serving service running independently)
>    Multi cluster support
>    Out-of-the-box node auto-scaling based on load/usage    <---- *

I found that serving has ability to auto-scale, but in helm charts ([triton](https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml-serving/templates/clearml-serving-triton-deployment.yaml) for example) I only found `replicas: 1` and didn't find an auto-scale implementation anywhere (like this https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/, for example).

Could you please clarify Clearml-serving scaling strategy and where can I find configuration files?

Thanks in advance.

**Comment by thepycoder** [comment]
Heya @senysenyseny16 !

Yeah, you are correct. The true master of the helm charts is @valeriano-manassero, so he can chip in if what I say is not correct, but in the case of Triton, you'd have to change the helm chart to enable autoscaling.

For example, to autoscale on GPUs, add a section somewhat like the following (depending on your needs):

```
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
```

or for GPU scaling:

```
spec:
 maxReplicas: 3  # Update this accordingly
 minReplicas: 1
 metrics:
 - type: Pods  # scale based on gpu
   pods:
     metric:
       name: DCGM_FI_DEV_GPU_UTIL
     target:
       type: AverageValue
       averageValue: 80
```

To read more about DCGM check [this link](https://developer.nvidia.com/blog/monitoring-gpus-in-kubernetes-with-dcgm/). Hope that helps!
